//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.ARTICULOS_RESERVA = new HashSet<ARTICULOS_RESERVA>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public int Tipo_Articulo { get; set; }
        public string Precio { get; set; }
    
        public virtual Precio Precio1 { get; set; }
        public virtual Tipo_Articulo Tipo_Articulo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULOS_RESERVA> ARTICULOS_RESERVA { get; set; }
    }
}
