//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public decimal codigo { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public decimal tipo_articulo_codigo { get; set; }
        public decimal reserva_reservaid { get; set; }
    
        public virtual reserva reserva { get; set; }
        public virtual tipo_articulo tipo_articulo { get; set; }
    }
}
