//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public string codigo_art { get; set; }
        public string nombre { get; set; }
        public int precio { get; set; }
        public int tipo_articulo_codigo_tipart { get; set; }
        public string reserva_reservaid { get; set; }
    
        public virtual reserva reserva { get; set; }
        public virtual tipo_articulo tipo_articulo { get; set; }
    }
}
