//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingid
    {
        public string codigo { get; set; }
        public string reserva_reservaid { get; set; }
        public string habitacion_codigo_hab { get; set; }
        public string reservaid { get; set; }
    
        public virtual habitacion habitacion { get; set; }
        public virtual reserva reserva { get; set; }
    }
}
