//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingID
    {
        public string Codigo { get; set; }
        public string Habitacion { get; set; }
        public string Reserva { get; set; }
    
        public virtual Habitacion Habitacion1 { get; set; }
        public virtual Reserva Reserva1 { get; set; }
    }
}
