//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivo
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public int Consecutivo1 { get; set; }
        public Nullable<bool> PoseePrefijo { get; set; }
        public string Prefijo { get; set; }
        public Nullable<bool> PoseeRango { get; set; }
        public Nullable<int> Minimo { get; set; }
        public Nullable<int> Maximo { get; set; }
    }
}
