//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consecutivo
    {
        public int codigo_cons { get; set; }
        public string descripcion { get; set; }
        public string consecutivo1 { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> minimo { get; set; }
        public Nullable<int> maximo { get; set; }
    }
}
