//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacion()
        {
            this.BookingID = new HashSet<BookingID>();
        }
    
        public string Codigo { get; set; }
        public int Numero { get; set; }
        public string Descripcion { get; set; }
        public int Est_Hab { get; set; }
        public string Precio { get; set; }
        public int Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingID> BookingID { get; set; }
        public virtual Est_Hab Est_Hab1 { get; set; }
        public virtual Precio Precio1 { get; set; }
        public virtual Tipo_Habitacion Tipo_Habitacion { get; set; }
    }
}
