//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public habitacion()
        {
            this.bookingid = new HashSet<bookingid>();
        }
    
        public decimal codigo { get; set; }
        public string descripcion { get; set; }
        public decimal estado_habitacion_codigo { get; set; }
        public decimal precio_codigo { get; set; }
        public decimal consecutivo_codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookingid> bookingid { get; set; }
        public virtual consecutivo consecutivo { get; set; }
        public virtual estado_habitacion estado_habitacion { get; set; }
        public virtual precio precio { get; set; }
    }
}
