//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_actividad
    {
        public int codigo_histact { get; set; }
        public string usuario_cedula { get; set; }
        public string actividad_codigo_act { get; set; }
    
        public virtual actividad actividad { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
