//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<BookingID> BookingID { get; set; }
        public virtual DbSet<Consecutivo> Consecutivo { get; set; }
        public virtual DbSet<Emisor> Emisor { get; set; }
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<Est_Hab> Est_Hab { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Historial_Actividad> Historial_Actividad { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<Tipo_Articulo> Tipo_Articulo { get; set; }
        public virtual DbSet<Tipo_Habitacion> Tipo_Habitacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int ACTUALIZA_ARTICULO(Nullable<int> pCodigo, string pNombre, Nullable<int> pPrecio, string pReserva)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            var pReservaParameter = pReserva != null ?
                new ObjectParameter("pReserva", pReserva) :
                new ObjectParameter("pReserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_ARTICULO", pCodigoParameter, pNombreParameter, pPrecioParameter, pReservaParameter);
        }
    
        public virtual int ACTUALIZA_BITACORA(string pCodigo, Nullable<System.DateTime> pFecha_hora, string pTipo, string pDescripcion)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pFecha_horaParameter = pFecha_hora.HasValue ?
                new ObjectParameter("pFecha_hora", pFecha_hora) :
                new ObjectParameter("pFecha_hora", typeof(System.DateTime));
    
            var pTipoParameter = pTipo != null ?
                new ObjectParameter("pTipo", pTipo) :
                new ObjectParameter("pTipo", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_BITACORA", pCodigoParameter, pFecha_horaParameter, pTipoParameter, pDescripcionParameter);
        }
    
        public virtual int ACTUALIZA_HABITACION(string pCodigo, string pDescripcion, Nullable<int> pEstado, Nullable<int> pPrecio)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pEstadoParameter = pEstado.HasValue ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(int));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_HABITACION", pCodigoParameter, pDescripcionParameter, pEstadoParameter, pPrecioParameter);
        }
    
        public virtual int ACTUALIZA_PRECIO(string pCodigo, Nullable<int> pTipo_habitacion, Nullable<int> pPrecio)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pTipo_habitacionParameter = pTipo_habitacion.HasValue ?
                new ObjectParameter("pTipo_habitacion", pTipo_habitacion) :
                new ObjectParameter("pTipo_habitacion", typeof(int));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_PRECIO", pCodigoParameter, pTipo_habitacionParameter, pPrecioParameter);
        }
    
        public virtual int ACTUALIZA_USUARIO(string pNombre, string pApellido1, string pApellido2, string pCorreo, string pUsuario, string pClave, Nullable<int> pRol, string pPregunta, string pRespuesta, Nullable<int> pEstado)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pApellido1Parameter = pApellido1 != null ?
                new ObjectParameter("pApellido1", pApellido1) :
                new ObjectParameter("pApellido1", typeof(string));
    
            var pApellido2Parameter = pApellido2 != null ?
                new ObjectParameter("pApellido2", pApellido2) :
                new ObjectParameter("pApellido2", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var pRolParameter = pRol.HasValue ?
                new ObjectParameter("pRol", pRol) :
                new ObjectParameter("pRol", typeof(int));
    
            var pPreguntaParameter = pPregunta != null ?
                new ObjectParameter("pPregunta", pPregunta) :
                new ObjectParameter("pPregunta", typeof(string));
    
            var pRespuestaParameter = pRespuesta != null ?
                new ObjectParameter("pRespuesta", pRespuesta) :
                new ObjectParameter("pRespuesta", typeof(string));
    
            var pEstadoParameter = pEstado.HasValue ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_USUARIO", pNombreParameter, pApellido1Parameter, pApellido2Parameter, pCorreoParameter, pUsuarioParameter, pClaveParameter, pRolParameter, pPreguntaParameter, pRespuestaParameter, pEstadoParameter);
        }
    
        public virtual int CAMBIO_PASS(string pUsername, string pPassword)
        {
            var pUsernameParameter = pUsername != null ?
                new ObjectParameter("pUsername", pUsername) :
                new ObjectParameter("pUsername", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CAMBIO_PASS", pUsernameParameter, pPasswordParameter);
        }
    
        public virtual int CLIENTE_REGISTRO(string pNombre, string pApellido1, string pApellido2, string pCorreo, string pUsuario, string pClave, string pPregunta, string pRespuesta, Nullable<int> pRol, Nullable<int> pEstado)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pApellido1Parameter = pApellido1 != null ?
                new ObjectParameter("pApellido1", pApellido1) :
                new ObjectParameter("pApellido1", typeof(string));
    
            var pApellido2Parameter = pApellido2 != null ?
                new ObjectParameter("pApellido2", pApellido2) :
                new ObjectParameter("pApellido2", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var pPreguntaParameter = pPregunta != null ?
                new ObjectParameter("pPregunta", pPregunta) :
                new ObjectParameter("pPregunta", typeof(string));
    
            var pRespuestaParameter = pRespuesta != null ?
                new ObjectParameter("pRespuesta", pRespuesta) :
                new ObjectParameter("pRespuesta", typeof(string));
    
            var pRolParameter = pRol.HasValue ?
                new ObjectParameter("pRol", pRol) :
                new ObjectParameter("pRol", typeof(int));
    
            var pEstadoParameter = pEstado.HasValue ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CLIENTE_REGISTRO", pNombreParameter, pApellido1Parameter, pApellido2Parameter, pCorreoParameter, pUsuarioParameter, pClaveParameter, pPreguntaParameter, pRespuestaParameter, pRolParameter, pEstadoParameter);
        }
    
        public virtual ObjectResult<CONSULTA_ACTIVIDAD_Result> CONSULTA_ACTIVIDAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_ACTIVIDAD_Result>("CONSULTA_ACTIVIDAD");
        }
    
        public virtual ObjectResult<CONSULTA_ARTICULO_Result> CONSULTA_ARTICULO(Nullable<int> pCodigo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_ARTICULO_Result>("CONSULTA_ARTICULO", pCodigoParameter);
        }
    
        public virtual ObjectResult<CONSULTA_BITACORA_Result> CONSULTA_BITACORA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_BITACORA_Result>("CONSULTA_BITACORA");
        }
    
        public virtual ObjectResult<CONSULTA_CONSECUTIVO_Result> CONSULTA_CONSECUTIVO(Nullable<int> pCodigo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_CONSECUTIVO_Result>("CONSULTA_CONSECUTIVO", pCodigoParameter);
        }
    
        public virtual ObjectResult<CONSULTA_ERROR_Result> CONSULTA_ERROR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_ERROR_Result>("CONSULTA_ERROR");
        }
    
        public virtual ObjectResult<CONSULTA_HABITACION_Result> CONSULTA_HABITACION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_HABITACION_Result>("CONSULTA_HABITACION");
        }
    
        public virtual ObjectResult<CONSULTA_PRECIO_Result> CONSULTA_PRECIO(Nullable<int> pCodigo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_PRECIO_Result>("CONSULTA_PRECIO", pCodigoParameter);
        }
    
        public virtual ObjectResult<CONSULTA_RESERVA_Result> CONSULTA_RESERVA(Nullable<int> pReserva)
        {
            var pReservaParameter = pReserva.HasValue ?
                new ObjectParameter("pReserva", pReserva) :
                new ObjectParameter("pReserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_RESERVA_Result>("CONSULTA_RESERVA", pReservaParameter);
        }
    
        public virtual ObjectResult<CONSULTA_ROL_Result> CONSULTA_ROL(Nullable<int> pCodigo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_ROL_Result>("CONSULTA_ROL", pCodigoParameter);
        }
    
        public virtual ObjectResult<CONSULTA_USUARIO_Result> CONSULTA_USUARIO(string pCorreo)
        {
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_USUARIO_Result>("CONSULTA_USUARIO", pCorreoParameter);
        }
    
        public virtual int ELIMINA_ACTIVIDAD(string pCodigo, string pNombre, string pDescripcion, string pDia, Nullable<System.DateTime> pHorainicio, Nullable<System.DateTime> pHorafinal)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pDiaParameter = pDia != null ?
                new ObjectParameter("pDia", pDia) :
                new ObjectParameter("pDia", typeof(string));
    
            var pHorainicioParameter = pHorainicio.HasValue ?
                new ObjectParameter("pHorainicio", pHorainicio) :
                new ObjectParameter("pHorainicio", typeof(System.DateTime));
    
            var pHorafinalParameter = pHorafinal.HasValue ?
                new ObjectParameter("pHorafinal", pHorafinal) :
                new ObjectParameter("pHorafinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_ACTIVIDAD", pCodigoParameter, pNombreParameter, pDescripcionParameter, pDiaParameter, pHorainicioParameter, pHorafinalParameter);
        }
    
        public virtual int ELIMINA_ARTICULO(Nullable<int> pCodigo, string pNombre, Nullable<int> pPrecio, string pReservaid)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            var pReservaidParameter = pReservaid != null ?
                new ObjectParameter("pReservaid", pReservaid) :
                new ObjectParameter("pReservaid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_ARTICULO", pCodigoParameter, pNombreParameter, pPrecioParameter, pReservaidParameter);
        }
    
        public virtual int ELIMINA_BITACORA(string pCodigo, Nullable<System.DateTime> pFecha_hora, string pTipo, string pDescripcion)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pFecha_horaParameter = pFecha_hora.HasValue ?
                new ObjectParameter("pFecha_hora", pFecha_hora) :
                new ObjectParameter("pFecha_hora", typeof(System.DateTime));
    
            var pTipoParameter = pTipo != null ?
                new ObjectParameter("pTipo", pTipo) :
                new ObjectParameter("pTipo", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_BITACORA", pCodigoParameter, pFecha_horaParameter, pTipoParameter, pDescripcionParameter);
        }
    
        public virtual int ELIMINA_CONSECUTIVO(Nullable<int> pCodigo, string descripcion, string consecutivo, string prefijo, Nullable<int> minimo, Nullable<int> maximo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var consecutivoParameter = consecutivo != null ?
                new ObjectParameter("consecutivo", consecutivo) :
                new ObjectParameter("consecutivo", typeof(string));
    
            var prefijoParameter = prefijo != null ?
                new ObjectParameter("prefijo", prefijo) :
                new ObjectParameter("prefijo", typeof(string));
    
            var minimoParameter = minimo.HasValue ?
                new ObjectParameter("minimo", minimo) :
                new ObjectParameter("minimo", typeof(int));
    
            var maximoParameter = maximo.HasValue ?
                new ObjectParameter("maximo", maximo) :
                new ObjectParameter("maximo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_CONSECUTIVO", pCodigoParameter, descripcionParameter, consecutivoParameter, prefijoParameter, minimoParameter, maximoParameter);
        }
    
        public virtual int ELIMINA_ERROR(Nullable<int> pCodigo, Nullable<System.DateTime> pFecha_hora, string pMensaje)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var pFecha_horaParameter = pFecha_hora.HasValue ?
                new ObjectParameter("pFecha_hora", pFecha_hora) :
                new ObjectParameter("pFecha_hora", typeof(System.DateTime));
    
            var pMensajeParameter = pMensaje != null ?
                new ObjectParameter("pMensaje", pMensaje) :
                new ObjectParameter("pMensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_ERROR", pCodigoParameter, pFecha_horaParameter, pMensajeParameter);
        }
    
        public virtual int ELIMINA_HABITACION(string pCodigo, string pDescripcion, Nullable<int> pEstado, Nullable<int> pPrecio)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pEstadoParameter = pEstado.HasValue ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(int));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_HABITACION", pCodigoParameter, pDescripcionParameter, pEstadoParameter, pPrecioParameter);
        }
    
        public virtual int ELIMINA_PRECIO(string pCodigo, Nullable<int> pTipo_habitacion, Nullable<int> pPrecio)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pTipo_habitacionParameter = pTipo_habitacion.HasValue ?
                new ObjectParameter("pTipo_habitacion", pTipo_habitacion) :
                new ObjectParameter("pTipo_habitacion", typeof(int));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_PRECIO", pCodigoParameter, pTipo_habitacionParameter, pPrecioParameter);
        }
    
        public virtual int ELIMINA_RESERVA(string pReserva, Nullable<System.DateTime> pFechaentrada, Nullable<System.DateTime> pFechasalida, Nullable<int> pCantidaddias, Nullable<bool> pCodigopromocional, Nullable<int> pCantidadultos, Nullable<int> pCantidniños, Nullable<bool> pMascota, string pMetodopago, Nullable<int> pPrecio)
        {
            var pReservaParameter = pReserva != null ?
                new ObjectParameter("pReserva", pReserva) :
                new ObjectParameter("pReserva", typeof(string));
    
            var pFechaentradaParameter = pFechaentrada.HasValue ?
                new ObjectParameter("pFechaentrada", pFechaentrada) :
                new ObjectParameter("pFechaentrada", typeof(System.DateTime));
    
            var pFechasalidaParameter = pFechasalida.HasValue ?
                new ObjectParameter("pFechasalida", pFechasalida) :
                new ObjectParameter("pFechasalida", typeof(System.DateTime));
    
            var pCantidaddiasParameter = pCantidaddias.HasValue ?
                new ObjectParameter("pCantidaddias", pCantidaddias) :
                new ObjectParameter("pCantidaddias", typeof(int));
    
            var pCodigopromocionalParameter = pCodigopromocional.HasValue ?
                new ObjectParameter("pCodigopromocional", pCodigopromocional) :
                new ObjectParameter("pCodigopromocional", typeof(bool));
    
            var pCantidadultosParameter = pCantidadultos.HasValue ?
                new ObjectParameter("pCantidadultos", pCantidadultos) :
                new ObjectParameter("pCantidadultos", typeof(int));
    
            var pCantidniñosParameter = pCantidniños.HasValue ?
                new ObjectParameter("pCantidniños", pCantidniños) :
                new ObjectParameter("pCantidniños", typeof(int));
    
            var pMascotaParameter = pMascota.HasValue ?
                new ObjectParameter("pMascota", pMascota) :
                new ObjectParameter("pMascota", typeof(bool));
    
            var pMetodopagoParameter = pMetodopago != null ?
                new ObjectParameter("pMetodopago", pMetodopago) :
                new ObjectParameter("pMetodopago", typeof(string));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_RESERVA", pReservaParameter, pFechaentradaParameter, pFechasalidaParameter, pCantidaddiasParameter, pCodigopromocionalParameter, pCantidadultosParameter, pCantidniñosParameter, pMascotaParameter, pMetodopagoParameter, pPrecioParameter);
        }
    
        public virtual int ELIMINA_USUARIO(string pNombre, string pApellido1, string pApellido2, string pCorreo, string pUsuario, string pClave, Nullable<int> pRol, string pPregunta, string pRespuesta, Nullable<int> pEstado)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pApellido1Parameter = pApellido1 != null ?
                new ObjectParameter("pApellido1", pApellido1) :
                new ObjectParameter("pApellido1", typeof(string));
    
            var pApellido2Parameter = pApellido2 != null ?
                new ObjectParameter("pApellido2", pApellido2) :
                new ObjectParameter("pApellido2", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var pRolParameter = pRol.HasValue ?
                new ObjectParameter("pRol", pRol) :
                new ObjectParameter("pRol", typeof(int));
    
            var pPreguntaParameter = pPregunta != null ?
                new ObjectParameter("pPregunta", pPregunta) :
                new ObjectParameter("pPregunta", typeof(string));
    
            var pRespuestaParameter = pRespuesta != null ?
                new ObjectParameter("pRespuesta", pRespuesta) :
                new ObjectParameter("pRespuesta", typeof(string));
    
            var pEstadoParameter = pEstado.HasValue ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_USUARIO", pNombreParameter, pApellido1Parameter, pApellido2Parameter, pCorreoParameter, pUsuarioParameter, pClaveParameter, pRolParameter, pPreguntaParameter, pRespuestaParameter, pEstadoParameter);
        }
    
        public virtual int EXISTE(Nullable<int> pCodigo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE", pCodigoParameter);
        }
    
        public virtual int INSERTA_ACTIVIDAD(string pNombre, string pDescripcion)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_ACTIVIDAD", pNombreParameter, pDescripcionParameter);
        }
    
        public virtual int INSERTA_BITACORA(string pTipo, string pDescripcion)
        {
            var pTipoParameter = pTipo != null ?
                new ObjectParameter("pTipo", pTipo) :
                new ObjectParameter("pTipo", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_BITACORA", pTipoParameter, pDescripcionParameter);
        }
    
        public virtual int INSERTA_CONSECUTIVO(Nullable<int> pCodigo, string pDescripcion, string pConsecutivo, Nullable<bool> pPoseePrefijo, string pPrefijo, Nullable<bool> pPoseeRango, Nullable<int> pMinimo, Nullable<int> pMaximo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pConsecutivoParameter = pConsecutivo != null ?
                new ObjectParameter("pConsecutivo", pConsecutivo) :
                new ObjectParameter("pConsecutivo", typeof(string));
    
            var pPoseePrefijoParameter = pPoseePrefijo.HasValue ?
                new ObjectParameter("pPoseePrefijo", pPoseePrefijo) :
                new ObjectParameter("pPoseePrefijo", typeof(bool));
    
            var pPrefijoParameter = pPrefijo != null ?
                new ObjectParameter("pPrefijo", pPrefijo) :
                new ObjectParameter("pPrefijo", typeof(string));
    
            var pPoseeRangoParameter = pPoseeRango.HasValue ?
                new ObjectParameter("pPoseeRango", pPoseeRango) :
                new ObjectParameter("pPoseeRango", typeof(bool));
    
            var pMinimoParameter = pMinimo.HasValue ?
                new ObjectParameter("pMinimo", pMinimo) :
                new ObjectParameter("pMinimo", typeof(int));
    
            var pMaximoParameter = pMaximo.HasValue ?
                new ObjectParameter("pMaximo", pMaximo) :
                new ObjectParameter("pMaximo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_CONSECUTIVO", pCodigoParameter, pDescripcionParameter, pConsecutivoParameter, pPoseePrefijoParameter, pPrefijoParameter, pPoseeRangoParameter, pMinimoParameter, pMaximoParameter);
        }
    
        public virtual int INSERTA_ERROR(Nullable<System.DateTime> pFecha_hora, string pMensaje)
        {
            var pFecha_horaParameter = pFecha_hora.HasValue ?
                new ObjectParameter("pFecha_hora", pFecha_hora) :
                new ObjectParameter("pFecha_hora", typeof(System.DateTime));
    
            var pMensajeParameter = pMensaje != null ?
                new ObjectParameter("pMensaje", pMensaje) :
                new ObjectParameter("pMensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_ERROR", pFecha_horaParameter, pMensajeParameter);
        }
    
        public virtual int INSERTA_HABITACION(Nullable<int> pNumero, string pDescripcion, Nullable<int> pEst_Hab, string pPrecio)
        {
            var pNumeroParameter = pNumero.HasValue ?
                new ObjectParameter("pNumero", pNumero) :
                new ObjectParameter("pNumero", typeof(int));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pEst_HabParameter = pEst_Hab.HasValue ?
                new ObjectParameter("pEst_Hab", pEst_Hab) :
                new ObjectParameter("pEst_Hab", typeof(int));
    
            var pPrecioParameter = pPrecio != null ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_HABITACION", pNumeroParameter, pDescripcionParameter, pEst_HabParameter, pPrecioParameter);
        }
    
        public virtual int INSERTA_RESERVA(Nullable<System.DateTime> pFecha_Entrada, Nullable<System.DateTime> pFecha_Salida, Nullable<int> pCantidad_Dias, Nullable<bool> pCodigo_Promocional, Nullable<int> pCantidad_Adultos, Nullable<int> pCantidad_Niños, Nullable<bool> pMascota, string pMetodo_Pago, Nullable<int> pPrecio, string pUsuario)
        {
            var pFecha_EntradaParameter = pFecha_Entrada.HasValue ?
                new ObjectParameter("pFecha_Entrada", pFecha_Entrada) :
                new ObjectParameter("pFecha_Entrada", typeof(System.DateTime));
    
            var pFecha_SalidaParameter = pFecha_Salida.HasValue ?
                new ObjectParameter("pFecha_Salida", pFecha_Salida) :
                new ObjectParameter("pFecha_Salida", typeof(System.DateTime));
    
            var pCantidad_DiasParameter = pCantidad_Dias.HasValue ?
                new ObjectParameter("pCantidad_Dias", pCantidad_Dias) :
                new ObjectParameter("pCantidad_Dias", typeof(int));
    
            var pCodigo_PromocionalParameter = pCodigo_Promocional.HasValue ?
                new ObjectParameter("pCodigo_Promocional", pCodigo_Promocional) :
                new ObjectParameter("pCodigo_Promocional", typeof(bool));
    
            var pCantidad_AdultosParameter = pCantidad_Adultos.HasValue ?
                new ObjectParameter("pCantidad_Adultos", pCantidad_Adultos) :
                new ObjectParameter("pCantidad_Adultos", typeof(int));
    
            var pCantidad_NiñosParameter = pCantidad_Niños.HasValue ?
                new ObjectParameter("pCantidad_Niños", pCantidad_Niños) :
                new ObjectParameter("pCantidad_Niños", typeof(int));
    
            var pMascotaParameter = pMascota.HasValue ?
                new ObjectParameter("pMascota", pMascota) :
                new ObjectParameter("pMascota", typeof(bool));
    
            var pMetodo_PagoParameter = pMetodo_Pago != null ?
                new ObjectParameter("pMetodo_Pago", pMetodo_Pago) :
                new ObjectParameter("pMetodo_Pago", typeof(string));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_RESERVA", pFecha_EntradaParameter, pFecha_SalidaParameter, pCantidad_DiasParameter, pCodigo_PromocionalParameter, pCantidad_AdultosParameter, pCantidad_NiñosParameter, pMascotaParameter, pMetodo_PagoParameter, pPrecioParameter, pUsuarioParameter);
        }
    
        public virtual int MODIFICA_CONSECUTIVO(Nullable<int> pCodigo, string pDescripcion, Nullable<bool> pPoseePrefijo, string pConsecutivo, string pPrefijo, Nullable<bool> pPoseeRango, Nullable<int> pMinimo, Nullable<int> pMaximo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pPoseePrefijoParameter = pPoseePrefijo.HasValue ?
                new ObjectParameter("pPoseePrefijo", pPoseePrefijo) :
                new ObjectParameter("pPoseePrefijo", typeof(bool));
    
            var pConsecutivoParameter = pConsecutivo != null ?
                new ObjectParameter("pConsecutivo", pConsecutivo) :
                new ObjectParameter("pConsecutivo", typeof(string));
    
            var pPrefijoParameter = pPrefijo != null ?
                new ObjectParameter("pPrefijo", pPrefijo) :
                new ObjectParameter("pPrefijo", typeof(string));
    
            var pPoseeRangoParameter = pPoseeRango.HasValue ?
                new ObjectParameter("pPoseeRango", pPoseeRango) :
                new ObjectParameter("pPoseeRango", typeof(bool));
    
            var pMinimoParameter = pMinimo.HasValue ?
                new ObjectParameter("pMinimo", pMinimo) :
                new ObjectParameter("pMinimo", typeof(int));
    
            var pMaximoParameter = pMaximo.HasValue ?
                new ObjectParameter("pMaximo", pMaximo) :
                new ObjectParameter("pMaximo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICA_CONSECUTIVO", pCodigoParameter, pDescripcionParameter, pPoseePrefijoParameter, pConsecutivoParameter, pPrefijoParameter, pPoseeRangoParameter, pMinimoParameter, pMaximoParameter);
        }
    
        public virtual int MODIFICA_ERROR(Nullable<int> pCodigo, Nullable<System.DateTime> pFecha_hora, string pMensaje)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var pFecha_horaParameter = pFecha_hora.HasValue ?
                new ObjectParameter("pFecha_hora", pFecha_hora) :
                new ObjectParameter("pFecha_hora", typeof(System.DateTime));
    
            var pMensajeParameter = pMensaje != null ?
                new ObjectParameter("pMensaje", pMensaje) :
                new ObjectParameter("pMensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICA_ERROR", pCodigoParameter, pFecha_horaParameter, pMensajeParameter);
        }
    
        public virtual int USUARIO_CONSULTA_ROL(string pCorreo)
        {
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USUARIO_CONSULTA_ROL", pCorreoParameter);
        }
    
        public virtual ObjectResult<USUARIO_LOGIN_Result> USUARIO_LOGIN(string pUsuario, string pPassword)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USUARIO_LOGIN_Result>("USUARIO_LOGIN", pUsuarioParameter, pPasswordParameter);
        }
    
        public virtual int USUARIO_REGISTRO(string pNombre, string pApellido1, string pApellido2, string pCorreo, string pUsuario, string pClave, Nullable<int> pRol, Nullable<int> pEstado)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pApellido1Parameter = pApellido1 != null ?
                new ObjectParameter("pApellido1", pApellido1) :
                new ObjectParameter("pApellido1", typeof(string));
    
            var pApellido2Parameter = pApellido2 != null ?
                new ObjectParameter("pApellido2", pApellido2) :
                new ObjectParameter("pApellido2", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var pRolParameter = pRol.HasValue ?
                new ObjectParameter("pRol", pRol) :
                new ObjectParameter("pRol", typeof(int));
    
            var pEstadoParameter = pEstado.HasValue ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USUARIO_REGISTRO", pNombreParameter, pApellido1Parameter, pApellido2Parameter, pCorreoParameter, pUsuarioParameter, pClaveParameter, pRolParameter, pEstadoParameter);
        }
    }
}
