//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<ARTICULOS_RESERVA> ARTICULOS_RESERVA { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<BookingID> BookingID { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Consecutivo> Consecutivo { get; set; }
        public virtual DbSet<Emisor> Emisor { get; set; }
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<Est_Hab> Est_Hab { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Historial_Actividad> Historial_Actividad { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<Tipo_Articulo> Tipo_Articulo { get; set; }
        public virtual DbSet<Tipo_Habitacion> Tipo_Habitacion { get; set; }
        public virtual DbSet<VIEW_PRECIOS> VIEW_PRECIOS { get; set; }
    
        public virtual int ACTUALIZA_ACTIVIDAD(string pCodigo, string pNombre, string pDesc)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pDescParameter = pDesc != null ?
                new ObjectParameter("pDesc", pDesc) :
                new ObjectParameter("pDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_ACTIVIDAD", pCodigoParameter, pNombreParameter, pDescParameter);
        }
    
        public virtual int ACTUALIZA_ADMIN_CLAVE(string pUsuario, string pCorreo, string pNuevaClave)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pNuevaClaveParameter = pNuevaClave != null ?
                new ObjectParameter("pNuevaClave", pNuevaClave) :
                new ObjectParameter("pNuevaClave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_ADMIN_CLAVE", pUsuarioParameter, pCorreoParameter, pNuevaClaveParameter);
        }
    
        public virtual int ACTUALIZA_CLIENTE_CLAVE(string pUsuario, string pCorreo, string pNuevaClave)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pNuevaClaveParameter = pNuevaClave != null ?
                new ObjectParameter("pNuevaClave", pNuevaClave) :
                new ObjectParameter("pNuevaClave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_CLIENTE_CLAVE", pUsuarioParameter, pCorreoParameter, pNuevaClaveParameter);
        }
    
        public virtual int ACTUALIZA_CLIENTE_ESTADO(string pUsuario, string pCorreo, string pEstado)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pEstadoParameter = pEstado != null ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_CLIENTE_ESTADO", pUsuarioParameter, pCorreoParameter, pEstadoParameter);
        }
    
        public virtual int ACTUALIZA_CONSECUTIVO(Nullable<int> pCodigo, string pDescripcion, string pConsecutivo, Nullable<bool> pPoseePrefijo, string pPrefijo, Nullable<bool> pPoseeRango, Nullable<int> pMinimo, Nullable<int> pMaximo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pConsecutivoParameter = pConsecutivo != null ?
                new ObjectParameter("pConsecutivo", pConsecutivo) :
                new ObjectParameter("pConsecutivo", typeof(string));
    
            var pPoseePrefijoParameter = pPoseePrefijo.HasValue ?
                new ObjectParameter("pPoseePrefijo", pPoseePrefijo) :
                new ObjectParameter("pPoseePrefijo", typeof(bool));
    
            var pPrefijoParameter = pPrefijo != null ?
                new ObjectParameter("pPrefijo", pPrefijo) :
                new ObjectParameter("pPrefijo", typeof(string));
    
            var pPoseeRangoParameter = pPoseeRango.HasValue ?
                new ObjectParameter("pPoseeRango", pPoseeRango) :
                new ObjectParameter("pPoseeRango", typeof(bool));
    
            var pMinimoParameter = pMinimo.HasValue ?
                new ObjectParameter("pMinimo", pMinimo) :
                new ObjectParameter("pMinimo", typeof(int));
    
            var pMaximoParameter = pMaximo.HasValue ?
                new ObjectParameter("pMaximo", pMaximo) :
                new ObjectParameter("pMaximo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_CONSECUTIVO", pCodigoParameter, pDescripcionParameter, pConsecutivoParameter, pPoseePrefijoParameter, pPrefijoParameter, pPoseeRangoParameter, pMinimoParameter, pMaximoParameter);
        }
    
        public virtual int ACTUALIZA_HABITACION(string pCodigo, string pNumero, string pDesc)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pNumeroParameter = pNumero != null ?
                new ObjectParameter("pNumero", pNumero) :
                new ObjectParameter("pNumero", typeof(string));
    
            var pDescParameter = pDesc != null ?
                new ObjectParameter("pDesc", pDesc) :
                new ObjectParameter("pDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_HABITACION", pCodigoParameter, pNumeroParameter, pDescParameter);
        }
    
        public virtual int ACTUALIZA_ROLES(string pCodigo, string pCorreo, Nullable<bool> pAdministrador, Nullable<bool> pSeguridad, Nullable<bool> pConsecutivo, Nullable<bool> pMantenimiento, Nullable<bool> pConsulta)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pAdministradorParameter = pAdministrador.HasValue ?
                new ObjectParameter("pAdministrador", pAdministrador) :
                new ObjectParameter("pAdministrador", typeof(bool));
    
            var pSeguridadParameter = pSeguridad.HasValue ?
                new ObjectParameter("pSeguridad", pSeguridad) :
                new ObjectParameter("pSeguridad", typeof(bool));
    
            var pConsecutivoParameter = pConsecutivo.HasValue ?
                new ObjectParameter("pConsecutivo", pConsecutivo) :
                new ObjectParameter("pConsecutivo", typeof(bool));
    
            var pMantenimientoParameter = pMantenimiento.HasValue ?
                new ObjectParameter("pMantenimiento", pMantenimiento) :
                new ObjectParameter("pMantenimiento", typeof(bool));
    
            var pConsultaParameter = pConsulta.HasValue ?
                new ObjectParameter("pConsulta", pConsulta) :
                new ObjectParameter("pConsulta", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZA_ROLES", pCodigoParameter, pCorreoParameter, pAdministradorParameter, pSeguridadParameter, pConsecutivoParameter, pMantenimientoParameter, pConsultaParameter);
        }
    
        public virtual ObjectResult<ADMIN_LOGIN_Result> ADMIN_LOGIN(string pUsuario, string pPassword)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADMIN_LOGIN_Result>("ADMIN_LOGIN", pUsuarioParameter, pPasswordParameter);
        }
    
        public virtual ObjectResult<CLIENTE_LOGIN_Result> CLIENTE_LOGIN(string pUsuario, string pPassword)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CLIENTE_LOGIN_Result>("CLIENTE_LOGIN", pUsuarioParameter, pPasswordParameter);
        }
    
        public virtual ObjectResult<CONSULTA_BITACORA_Result> CONSULTA_BITACORA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_BITACORA_Result>("CONSULTA_BITACORA");
        }
    
        public virtual ObjectResult<CONSULTA_CLIENTEACTIVO_Result> CONSULTA_CLIENTEACTIVO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_CLIENTEACTIVO_Result>("CONSULTA_CLIENTEACTIVO");
        }
    
        public virtual ObjectResult<CONSULTA_ERROR_Result> CONSULTA_ERROR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_ERROR_Result>("CONSULTA_ERROR");
        }
    
        public virtual ObjectResult<CONSULTA_HABITACIONESLISTAS_Result> CONSULTA_HABITACIONESLISTAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTA_HABITACIONESLISTAS_Result>("CONSULTA_HABITACIONESLISTAS");
        }
    
        public virtual int ELIMINA_ACTIVIDAD(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_ACTIVIDAD", pCodigoParameter);
        }
    
        public virtual int ELIMINA_HABITACION(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_HABITACION", pCodigoParameter);
        }
    
        public virtual int ELIMINA_PRECIO(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINA_PRECIO", pCodigoParameter);
        }
    
        public virtual int EXISTE_ACTIVIDAD(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_ACTIVIDAD", pCodigoParameter);
        }
    
        public virtual int EXISTE_ADMIN(string pUsuario, string pCorreo)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_ADMIN", pUsuarioParameter, pCorreoParameter);
        }
    
        public virtual int EXISTE_ARTICULO(Nullable<int> pCodigo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_ARTICULO", pCodigoParameter);
        }
    
        public virtual int EXISTE_BOOKINGID(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_BOOKINGID", pCodigoParameter);
        }
    
        public virtual int EXISTE_CLIENTE(string pUsuario, string pCorreo)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_CLIENTE", pUsuarioParameter, pCorreoParameter);
        }
    
        public virtual int EXISTE_CONSECUTIVO(Nullable<int> pCodigo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_CONSECUTIVO", pCodigoParameter);
        }
    
        public virtual int EXISTE_HABITACION(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_HABITACION", pCodigoParameter);
        }
    
        public virtual int EXISTE_PRECIO(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_PRECIO", pCodigoParameter);
        }
    
        public virtual int EXISTE_RESERVA(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXISTE_RESERVA", pCodigoParameter);
        }
    
        public virtual int INSERTA_ACTIVIDAD(string pNombre, string pDescripcion)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_ACTIVIDAD", pNombreParameter, pDescripcionParameter);
        }
    
        public virtual int INSERTA_ADMIN(string pNombre, string pApellido1, string pApellido2, string pCorreo, string pUsuario, string pClave, Nullable<bool> pAdministrador, Nullable<bool> pSeguridad, Nullable<bool> pConsecutivo, Nullable<bool> pMantenimiento, Nullable<bool> pConsulta)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pApellido1Parameter = pApellido1 != null ?
                new ObjectParameter("pApellido1", pApellido1) :
                new ObjectParameter("pApellido1", typeof(string));
    
            var pApellido2Parameter = pApellido2 != null ?
                new ObjectParameter("pApellido2", pApellido2) :
                new ObjectParameter("pApellido2", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var pAdministradorParameter = pAdministrador.HasValue ?
                new ObjectParameter("pAdministrador", pAdministrador) :
                new ObjectParameter("pAdministrador", typeof(bool));
    
            var pSeguridadParameter = pSeguridad.HasValue ?
                new ObjectParameter("pSeguridad", pSeguridad) :
                new ObjectParameter("pSeguridad", typeof(bool));
    
            var pConsecutivoParameter = pConsecutivo.HasValue ?
                new ObjectParameter("pConsecutivo", pConsecutivo) :
                new ObjectParameter("pConsecutivo", typeof(bool));
    
            var pMantenimientoParameter = pMantenimiento.HasValue ?
                new ObjectParameter("pMantenimiento", pMantenimiento) :
                new ObjectParameter("pMantenimiento", typeof(bool));
    
            var pConsultaParameter = pConsulta.HasValue ?
                new ObjectParameter("pConsulta", pConsulta) :
                new ObjectParameter("pConsulta", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_ADMIN", pNombreParameter, pApellido1Parameter, pApellido2Parameter, pCorreoParameter, pUsuarioParameter, pClaveParameter, pAdministradorParameter, pSeguridadParameter, pConsecutivoParameter, pMantenimientoParameter, pConsultaParameter);
        }
    
        public virtual int INSERTA_ARTICULO(string pNombre, Nullable<int> pTipo, string pPrecio)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pTipoParameter = pTipo.HasValue ?
                new ObjectParameter("pTipo", pTipo) :
                new ObjectParameter("pTipo", typeof(int));
    
            var pPrecioParameter = pPrecio != null ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_ARTICULO", pNombreParameter, pTipoParameter, pPrecioParameter);
        }
    
        public virtual int INSERTA_ARTICULOSRESERVA(Nullable<int> pCantidad, Nullable<int> pArticulo, string pReserva)
        {
            var pCantidadParameter = pCantidad.HasValue ?
                new ObjectParameter("pCantidad", pCantidad) :
                new ObjectParameter("pCantidad", typeof(int));
    
            var pArticuloParameter = pArticulo.HasValue ?
                new ObjectParameter("pArticulo", pArticulo) :
                new ObjectParameter("pArticulo", typeof(int));
    
            var pReservaParameter = pReserva != null ?
                new ObjectParameter("pReserva", pReserva) :
                new ObjectParameter("pReserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_ARTICULOSRESERVA", pCantidadParameter, pArticuloParameter, pReservaParameter);
        }
    
        public virtual int INSERTA_BITACORA(string pTipo, string pDescripcion)
        {
            var pTipoParameter = pTipo != null ?
                new ObjectParameter("pTipo", pTipo) :
                new ObjectParameter("pTipo", typeof(string));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_BITACORA", pTipoParameter, pDescripcionParameter);
        }
    
        public virtual int INSERTA_BOOKINGID(string pHabitacion, string pReserva)
        {
            var pHabitacionParameter = pHabitacion != null ?
                new ObjectParameter("pHabitacion", pHabitacion) :
                new ObjectParameter("pHabitacion", typeof(string));
    
            var pReservaParameter = pReserva != null ?
                new ObjectParameter("pReserva", pReserva) :
                new ObjectParameter("pReserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_BOOKINGID", pHabitacionParameter, pReservaParameter);
        }
    
        public virtual int INSERTA_CLIENTE(string pNombre, string pApellido1, string pApellido2, string pCorreo, string pUsuario, string pClave, string pPregunta, string pRespuesta, Nullable<int> pEstado)
        {
            var pNombreParameter = pNombre != null ?
                new ObjectParameter("pNombre", pNombre) :
                new ObjectParameter("pNombre", typeof(string));
    
            var pApellido1Parameter = pApellido1 != null ?
                new ObjectParameter("pApellido1", pApellido1) :
                new ObjectParameter("pApellido1", typeof(string));
    
            var pApellido2Parameter = pApellido2 != null ?
                new ObjectParameter("pApellido2", pApellido2) :
                new ObjectParameter("pApellido2", typeof(string));
    
            var pCorreoParameter = pCorreo != null ?
                new ObjectParameter("pCorreo", pCorreo) :
                new ObjectParameter("pCorreo", typeof(string));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var pPreguntaParameter = pPregunta != null ?
                new ObjectParameter("pPregunta", pPregunta) :
                new ObjectParameter("pPregunta", typeof(string));
    
            var pRespuestaParameter = pRespuesta != null ?
                new ObjectParameter("pRespuesta", pRespuesta) :
                new ObjectParameter("pRespuesta", typeof(string));
    
            var pEstadoParameter = pEstado.HasValue ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_CLIENTE", pNombreParameter, pApellido1Parameter, pApellido2Parameter, pCorreoParameter, pUsuarioParameter, pClaveParameter, pPreguntaParameter, pRespuestaParameter, pEstadoParameter);
        }
    
        public virtual int INSERTA_CONSECUTIVO(Nullable<int> pCodigo, string pDescripcion, string pConsecutivo, Nullable<bool> pPoseePrefijo, string pPrefijo, Nullable<bool> pPoseeRango, Nullable<int> pMinimo, Nullable<int> pMaximo)
        {
            var pCodigoParameter = pCodigo.HasValue ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(int));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pConsecutivoParameter = pConsecutivo != null ?
                new ObjectParameter("pConsecutivo", pConsecutivo) :
                new ObjectParameter("pConsecutivo", typeof(string));
    
            var pPoseePrefijoParameter = pPoseePrefijo.HasValue ?
                new ObjectParameter("pPoseePrefijo", pPoseePrefijo) :
                new ObjectParameter("pPoseePrefijo", typeof(bool));
    
            var pPrefijoParameter = pPrefijo != null ?
                new ObjectParameter("pPrefijo", pPrefijo) :
                new ObjectParameter("pPrefijo", typeof(string));
    
            var pPoseeRangoParameter = pPoseeRango.HasValue ?
                new ObjectParameter("pPoseeRango", pPoseeRango) :
                new ObjectParameter("pPoseeRango", typeof(bool));
    
            var pMinimoParameter = pMinimo.HasValue ?
                new ObjectParameter("pMinimo", pMinimo) :
                new ObjectParameter("pMinimo", typeof(int));
    
            var pMaximoParameter = pMaximo.HasValue ?
                new ObjectParameter("pMaximo", pMaximo) :
                new ObjectParameter("pMaximo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_CONSECUTIVO", pCodigoParameter, pDescripcionParameter, pConsecutivoParameter, pPoseePrefijoParameter, pPrefijoParameter, pPoseeRangoParameter, pMinimoParameter, pMaximoParameter);
        }
    
        public virtual int INSERTA_ERROR(Nullable<System.DateTime> pFecha_hora, string pMensaje)
        {
            var pFecha_horaParameter = pFecha_hora.HasValue ?
                new ObjectParameter("pFecha_hora", pFecha_hora) :
                new ObjectParameter("pFecha_hora", typeof(System.DateTime));
    
            var pMensajeParameter = pMensaje != null ?
                new ObjectParameter("pMensaje", pMensaje) :
                new ObjectParameter("pMensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_ERROR", pFecha_horaParameter, pMensajeParameter);
        }
    
        public virtual int INSERTA_HABITACION(Nullable<int> pNumero, string pDescripcion, Nullable<int> pEst_Hab, string pPrecio)
        {
            var pNumeroParameter = pNumero.HasValue ?
                new ObjectParameter("pNumero", pNumero) :
                new ObjectParameter("pNumero", typeof(int));
    
            var pDescripcionParameter = pDescripcion != null ?
                new ObjectParameter("pDescripcion", pDescripcion) :
                new ObjectParameter("pDescripcion", typeof(string));
    
            var pEst_HabParameter = pEst_Hab.HasValue ?
                new ObjectParameter("pEst_Hab", pEst_Hab) :
                new ObjectParameter("pEst_Hab", typeof(int));
    
            var pPrecioParameter = pPrecio != null ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_HABITACION", pNumeroParameter, pDescripcionParameter, pEst_HabParameter, pPrecioParameter);
        }
    
        public virtual int INSERTA_PRECIO(Nullable<int> pPrecio)
        {
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_PRECIO", pPrecioParameter);
        }
    
        public virtual int INSERTA_RESERVA(Nullable<System.DateTime> pFecha_Entrada, Nullable<System.DateTime> pFecha_Salida, Nullable<int> pCantidad_Dias, Nullable<bool> pCodigo_Promocional, Nullable<int> pCantidad_Adultos, Nullable<int> pCantidad_Niños, Nullable<bool> pMascota, string pMetodo_Pago, Nullable<int> pPrecio, string pUsuario)
        {
            var pFecha_EntradaParameter = pFecha_Entrada.HasValue ?
                new ObjectParameter("pFecha_Entrada", pFecha_Entrada) :
                new ObjectParameter("pFecha_Entrada", typeof(System.DateTime));
    
            var pFecha_SalidaParameter = pFecha_Salida.HasValue ?
                new ObjectParameter("pFecha_Salida", pFecha_Salida) :
                new ObjectParameter("pFecha_Salida", typeof(System.DateTime));
    
            var pCantidad_DiasParameter = pCantidad_Dias.HasValue ?
                new ObjectParameter("pCantidad_Dias", pCantidad_Dias) :
                new ObjectParameter("pCantidad_Dias", typeof(int));
    
            var pCodigo_PromocionalParameter = pCodigo_Promocional.HasValue ?
                new ObjectParameter("pCodigo_Promocional", pCodigo_Promocional) :
                new ObjectParameter("pCodigo_Promocional", typeof(bool));
    
            var pCantidad_AdultosParameter = pCantidad_Adultos.HasValue ?
                new ObjectParameter("pCantidad_Adultos", pCantidad_Adultos) :
                new ObjectParameter("pCantidad_Adultos", typeof(int));
    
            var pCantidad_NiñosParameter = pCantidad_Niños.HasValue ?
                new ObjectParameter("pCantidad_Niños", pCantidad_Niños) :
                new ObjectParameter("pCantidad_Niños", typeof(int));
    
            var pMascotaParameter = pMascota.HasValue ?
                new ObjectParameter("pMascota", pMascota) :
                new ObjectParameter("pMascota", typeof(bool));
    
            var pMetodo_PagoParameter = pMetodo_Pago != null ?
                new ObjectParameter("pMetodo_Pago", pMetodo_Pago) :
                new ObjectParameter("pMetodo_Pago", typeof(string));
    
            var pPrecioParameter = pPrecio.HasValue ?
                new ObjectParameter("pPrecio", pPrecio) :
                new ObjectParameter("pPrecio", typeof(int));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTA_RESERVA", pFecha_EntradaParameter, pFecha_SalidaParameter, pCantidad_DiasParameter, pCodigo_PromocionalParameter, pCantidad_AdultosParameter, pCantidad_NiñosParameter, pMascotaParameter, pMetodo_PagoParameter, pPrecioParameter, pUsuarioParameter);
        }
    
        public virtual ObjectResult<OBTENER_ROLES_Result> OBTENER_ROLES(string pCodigo)
        {
            var pCodigoParameter = pCodigo != null ?
                new ObjectParameter("pCodigo", pCodigo) :
                new ObjectParameter("pCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OBTENER_ROLES_Result>("OBTENER_ROLES", pCodigoParameter);
        }
    }
}
