//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividad> actividad { get; set; }
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<bitacora> bitacora { get; set; }
        public virtual DbSet<bookingid> bookingid { get; set; }
        public virtual DbSet<consecutivo> consecutivo { get; set; }
        public virtual DbSet<emisor> emisor { get; set; }
        public virtual DbSet<error> error { get; set; }
        public virtual DbSet<est_hab> est_hab { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<habitacion> habitacion { get; set; }
        public virtual DbSet<historial_actividad> historial_actividad { get; set; }
        public virtual DbSet<precio> precio { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tarjeta> tarjeta { get; set; }
        public virtual DbSet<tipo_articulo> tipo_articulo { get; set; }
        public virtual DbSet<tipo_habitacion> tipo_habitacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
