//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Mandiola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.articulo = new HashSet<articulo>();
            this.bookingid = new HashSet<bookingid>();
        }
    
        public decimal reservaid { get; set; }
        public System.DateTime fechaentrada { get; set; }
        public System.DateTime fechasalida { get; set; }
        public decimal cantidaddias { get; set; }
        public string codigopromocional { get; set; }
        public decimal cantidadadultos { get; set; }
        public decimal cantidadniños { get; set; }
        public string mascota { get; set; }
        public string metodopago { get; set; }
        public Nullable<decimal> precio { get; set; }
        public decimal usuario_cedula { get; set; }
        public decimal consecutivo_codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulo> articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookingid> bookingid { get; set; }
        public virtual consecutivo consecutivo { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
